db_pg {
  pg_host_conf = ${?PG_HOST}
  pg_port_conf = ${?PG_PORT}
  pg_user_conf = ${?PG_USER}
  pg_password_conf = ${?PG_PASSWORD}
  pg_database_conf = ${?PG_DATABASE}
  pg_driver_conf = ${?PG_DRIVER}
}